require 'open-uri'

module Utilities
  DRYRUN = ENV['DRYRUN'] || false

  LINEBREAK = (0..80).inject('') { |memo, member| memo + '-' }

  def self.dryrun?
    Utilities::DRYRUN
  end

  def self.log(task)
    puts "", "#{task}", Utilities::LINEBREAK
  end

  def self.execute(command)
    system command unless self.dryrun?
  end

  def self.backticks(command)
    `#{command}` unless self.dryrun?
  end

end

task :upgrade do
  upgrade = "sudo apt-get upgrade"
  Utilities::log upgrade
  Utilities::execute upgrade
end

task :update do
  update = "sudo apt-get update"
  Utilities::log update
  Utilities::execute update
end

task :software_properties_common do
  software_properties_common = "software_properties_common"
  Utilities::log software_properties_common
  Utilities::execute software_properties_common
end

task :inotify_tools do
  inotify_tools = "inotify-tools"
  Utilities::log inotify_tools
  Utilities::execute inotify_tools
end

task :ssh do
  keygen = "ssh-keygen -t rsa"
  Utilities::log keygen
  Utilities::execute keygen
end

task system: [:update, :upgrade]

task :git do
  git = "sudo apt-get install git"
  Utilities::log git
  Utilities::execute git

  git_config_email = 'git config --global user.email pdoherty@protonmail.com'
  Utilities::log git_config_email
  Utilities::execute git_config_email

  git_config_username = 'git config --global user.name "Peter Doherty"'
  Utilities::log git_config_username
  Utilities::execute git_config_username

  git_config_editor = 'git config --global core.editor vim'
  Utilities::log git_config_editor
  Utilities::execute git_config_editor
end

task :vundle do
  download_vundle = "git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim"
  Utilities::log download_vundle
  Utilities::execute download_vundle

  install_vundle = "vim +PluginInstall +qall"
  Utilities::log install_vundle
  Utilities::execute install_vundle
end

task :pathogen do
  download_and_install_pathogen = "mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim"
  Utilities::log download_and_install_pathogen
  Utilities::execute download_and_install_pathogen
end

task :_vim do
  vim = "sudo apt-get install vim-gtk"
  Utilities::log vim
  Utilities::execute vim
end

task vim: [:_vim, :pathogen, :vundle]

task :curl do
  curl = "sudo apt-get install curl"
  Utilities::log curl
  Utilities::execute curl
end

task :heroku do
  Utilities::log "download and execute heroku toolbelt installer"
  Utilities::execute "wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh"
end

task :xsel do
  xsel = "sudo apt-get install xsel"
  Utilities::log xsel
  Utilities::execute xsel
end

task :xchat do
  xchat = "sudo apt-get install xchat"
  Utilities::log xchat
  Utilities::execute xchat
end

task :ack do
  ack = "sudo apt-get install ack-grep"
  Utilities::log ack
  Utilities::execute ack
end

task :_tmux do
  tmux = "sudo apt-get install tmux"
  Utilities::log tmux
  Utilities::execute tmux
end

task :tmux_plugins do
  install_tpm = "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
  Utilities::log install_tpm
  Utilities::execute install_tpm

  install_plugins = "tmux run-shell ~/.tmux/plugins/tpm/bindings/install_plugins && tmux send-keys C-m"
  Utilities::log install_plugins
  Utilities::execute install_plugins
end

task tmux: [:_tmux, :tmux_plugins]

task :tree do
  tree = "sudo apt-get install tree"
  Utilities::log tree
  Utilities::execute tree
end

task :sublime_text do
  install = "sudo apt-get install sublime-text"
  Utilities::log install
  Utilities::execute install
end

task :editorconfig do
  install = "sudo apt-get install editorconfig"
  Utilities::log install
  Utilities::execute install
end

task editors: [:vim, :sublime_text, :editorconfig]

task :rvm do
  add_keys = "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"
  Utilities::log add_keys
  Utilities::execute add_keys

  download_install_script = "curl -sSL https://get.rvm.io | bash -s stable --ruby"
  Utilities::log download_install_script
  Utilities::execute download_install_script
end

task ruby: [:rvm]

task :redis do
  install_redis_dependencies = "sudo apt-get -y install build-essential tcl8.5"
  Utilities::log install_redis_dependencies
  Utilities::execute install_redis_dependencies

  download_redis = "cd ~ && wget http://download.redis.io/releases/redis-3.2.7.tar.gz"
  Utilities::log download_redis
  Utilities::execute download_redis

  install_redis = <<~EOF
    cd ~ &&
    tar xzf redis-3.2.7.tar.gz &&
    cd redis-3.2.7 &&
    make &&
    make test &&
    sudo make install &&
    cd utils &&
    sudo ./install_server.sh
  EOF
  Utilities::log install_redis
  Utilities::execute install_redis

  start_redis_on_boot = "sudo update-rc.d redis_6379 defaults"
  Utilities::log start_redis_on_boot
  Utilities::execute start_redis_on_boot
end

task :dateutils do
  dateutils = "sudo apt-get install dateutils"
  Utilities::log dateutils
  Utilities::execute dateutils
end

task :postgres do
  postgres = "sudo apt-get install postgresql postgresql-server-dev-all"
  Utilities::log postgres
  Utilities::execute postgres
end

task :elm do
  elm = "npm install -g elm"
  Utilities::log elm
  Utilities::execute elm
end

task npms: [:elm]

task :nvm do
  version = 'stable'

  Utilities::log "download and install nvm"
  Utilities::execute "curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash"

  Utilities::log "install latest nvm"
  Utilities::execute ". ~/.nvm/nvm.sh && nvm install #{version}"

  # use_stable_as_default = 'nvm alias default stable'
  # Utilities::log "append `#{use_stable_as_default}` to .bashrc"
  # Utilities::execute "echo '#{use_stable_as_default}' >> ~/.bashrc"
end

task node: [:nvm, :npms]

task :jre do
  jre = "sudo apt-get install default-jre"
  Utilities::log jre
  Utilities::execute jre
end

task :jdk do
  jdk = "sudo apt-get install default-jdk"
  Utilities::log jdk
  Utilities::execute jdk
end

task :java_home do
  Utilities::log "set JAVA_HOME"
  path = Utilities::backticks("which java").chomp
  Utilities::execute "echo JAVA_HOME=#{path} >> ~/.bashrc"
end

task java: [:jre, :jdk, :java_home]

task :leinengen do
  Utilities::log "download lein install script"
  Utilities::execute "wget -O lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"

  Utilities::log "move lein into path"
  Utilities::execute "mv lein ~/bin"

  Utilities::log "make lein executable"
  Utilities::execute "chmod 755 ~/bin/lein"

  Utilities::log "install lein"
  Utilities::execute "bash ~/bin/lein"
end

task :boot do
  url = "https://raw.githubusercontent.com/boot-clj/boot/master/version.properties"
  content = open(url).read
  version = content.split('version=').last.chomp

  Utilities::log "download boot install script - version #{version}"
  Utilities::execute "wget -O boot https://github.com/boot-clj/boot/releases/download/#{version}/boot.sh"

  Utilities::log "chmod a+x boot"
  Utilities::execute "chmod a+x boot"

  Utilities::log "sudo mv boot /usr/local/bin"
  Utilities::execute "sudo mv boot /usr/local/bin"
end

task clojure: [:leinengen, :boot]

task :dotfiles do
  dotfiles_path = "https://github.com/ethagnawl/dotfiles"
  Utilities::log "clone dotfiles"
  Utilities::execute "cd ~ && git clone #{dotfiles_path}"

  Utilities::log "symlink default.gems"
  Utilities::execute "cd ~/.rvm/gemsets && ln -s ~/dotfiles/default.gems ."

  Utilities::log "symlink .vimrc"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.vimrc ."

  Utilities::log "symlink .tmux.conf"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.tmux.conf ."

  Utilities::log "symlink .gemrc"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.gemrc ."

  Utilities::log "symlink .pryrc"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.pryrc ."

  Utilities::log "symlink .inputrc"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.inputrc ."

  Utilities::log "symlink .nvmrc"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.nvmrc ."

  Utilities::log "symlink ssh config"
  Utilities::execute "cd ~ && ln -s ~/dotfiles/.ssh-config ~/.ssh/config"

  Utilities::log "symlink lubuntu-rc.xml"
  Utilities::execute "ln -s ~/dotfiles/linux/lubuntu/lubuntu-rc.xml ~/.config/openbox/"

  Utilities::log "symlink firefox.desktop"
  Utilities::execute "ln -s ~/dotfiles/linux/LXDE/firefox.desktop ~/.config/autostart/"

  Utilities::log "symlink terminal.desktop"
  Utilities::execute "ln -s ~/dotfiles/linux/LXDE/terminal.desktop ~/.config/autostart/"

  Utilities::log "symlink touchpad.desktop"
  Utilities::execute "ln -s ~/dotfiles/linux/LXDE/touchpad.desktop ~/.config/autostart/"

  Utilities::log "copy .editorconfig"
  Utilities::execute "cd ~ && cp .editorconfig ~/.editorconfig"

  Utilities::log "append `source ~/dotfiles/bashrc` to .bashrc"
  Utilities::execute "echo 'source ~/dotfiles/bashrc' >> ~/.bashrc"

  Utilities::log "copy battery.sh to ~"
  Utilities::execute "cd ~ && cp scripts/battery.sh ~/battery.sh"

  Utilities::log "copy screenshot.sh to /usr/local/bin"
  Utilities::execute "cp scripts/screenshot.sh /usr/local/bin/screenshot.sh"
end

task :racket do
  racket = "sudo apt-get install racket"
  Utilities::log racket
  Utilities::execute racket
end

task :stack do
  stack = "curl -sSL https://get.haskellstack.org/ | sh"
  Utilities::log stack
  Utilities::execute stack
end

task :ghc do
  haskell = "sudo apt-get install ghc"
  Utilities::log haskell
  Utilities::execute haskell
end

task haskell: [
  :ghc,
  :stack
]

task :gcc do
  gcc = "sudo apt-get install gcc"
  Utilities::log gcc
  Utilities::execute gcc
end

task :gdb do
  gdb = "sudo apt-get install gdb"
  Utilities::log gdb
  Utilities::execute gdb
end

task c: [:gcc, :gdb]

task :keepassx do
  keepassx = "sudo apt-get install keepassx"
  Utilities::log keepassx
  Utilities::execute keepassx
end

task :dmenu do
  keepassx = "sudo apt-get install dmenu"
  Utilities::log dmenu
  Utilities::execute dmenu
end

task :htop do
  htop = "sudo apt-get install htop"
  Utilities::log htop
  Utilities::execute htop
end

task :rlwrap do
  rlwrap = "sudo apt-get install rlwrap"
  Utilities::log rlwrap
  Utilities::execute rlwrap
end

task :gimp do
  gimp = "sudo apt-get install gimp"
  Utilities::log gimp
  Utilities::execute gimp
end

task :chrome do
  get_key = "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
  Utilities::log get_key
  Utilities::execute get_key

  add_ppa = 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  Utilities::log add_ppa
  Utilities::execute add_ppa

  Rake::Task["update"].execute

  chrome = "sudo apt-get install google-chrome-unstable"
  Utilities::log chrome
  Utilities::execute chrome
end

task :dropbox do
  dropbox = "sudo apt-get install nautilus-dropbox"
  Utilities::log dropbox
  Utilities::execute dropbox
end

task :torbrowser_launcher do
  add_torbrowser_launcher_ppa = "sudo add-apt-repository ppa:micahflee/ppa"
  Utilities::log add_torbrowser_launcher_ppa
  Utilities::execute add_torbrowser_launcher_ppa

  Rake::Task["update"].execute

  install_torbrowser_launcher = "sudo apt-get install torbrowser-launcher"
  Utilities::log install_torbrowser_launcher
  Utilities::execute install_torbrowser_launcher
end

task :docker do
  docker = "curl -fsSL https://get.docker.com/ | sh"
  Utilities::log "install docker via `#{docker}`"
  Utilities::execute docker
end

task :typespeed do
  typespeed = 'sudo apt-get install typespeed'
  Utilities::log typespeed
  Utilities::execute typespeed
end

task :flameshot do
  # backports?
  flameshot = 'sudo apt-get install flameshot'
  Utilities::log flameshot
  Utilities::execute flameshot
end

task :bleachbit do
  bleachbit = 'sudo apt-get install bleachbit'
  Utilities::log bleachbit
  Utilities::execute bleachbit
end

task :inxi do
  inxi = 'sudo apt-get install inxi'
  Utilities::log inxi
  Utilities::execute inxi
end

task applications: [
  :keepassx,
  :chrome,
  :dropbox,
  :dmenu,
  :rlwrap,
  :htop,
  :gimp,
  :torbrowser_launcher,
  :typespeed,
  :flameshot,
  :bleachbit,
  :inxi
]

task :chkrootkit do
  chkrootkit = 'sudo apt-get install chkrootkit'
  Utilities::log chkrootkit
  Utilities::execute chkrootkit
end

task security: [
  :chkrootkit
]

task linux: [
              :system,
              :software_properties_common,
              :inotify_tools,
              :ssh,
              :git,
              :ack,
              :tmux,
              :tree,
              :xsel,
              :xchat,
              :curl,
              :heroku,
              :ruby,
              :dotfiles,
              :editors,
              :redis,
              :postgres,
              :c,
              :node,
              :java,
              :clojure,
              :haskell,
              :racket,
              :docker,
              :applications,
              :security,
              :dateutils
            ] do |t|

end

task default: %w[linux]
